const SET_TOKEN = "SET_TOKEN"
const SET_ROLE = "SET_ROLE"
const REMOVE_ROLE = "REMOVE_ROLE"
const REMOVE_TOKEN = "REMOVE_TOKEN"
const SET_SEARCH_INFO = "SET_SEARCH_INFO"

export {
  SET_TOKEN,
  SET_ROLE,
  REMOVE_ROLE,
  REMOVE_TOKEN,
  SET_SEARCH_INFO,
}